version: "3.3"

services:
    api:
        build: 
            context: "docker-api"
        volumes: 
            - ./docker-api/:/app/
        ports:
            - 8088:8000

    mongo:
        image: mongo
        ports:
            - 27090:27017
        volumes:
            - mongo_data:/data/db

    postgres:
        image: postgres:9.6
        logging:
            options:
                max-size: 10m
                max-file: "3"
        env_file:
        - .env
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
        - 5432:5432
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U javaapp"]
            interval: 10s
            timeout: 5s
            retries: 5            

volumes:
    mongo_data:
    postgres_data:
    
